#!/bin/bash

cd ..

singularity exec --nv --nvccli --bind /run/shm IMS-Toucan.sif python run_training_pipeline.py taco_aridialect --config paramsspo.ini

singularity exec --nv --nvccli --bind /run/shm IMS-Toucan.sif python run_training_pipeline.py taco_aridialect --config paramsspo.ini
